### ISSUE TITLE
Update code block and mermaid styles

### ISSUE THREAD

**Issue by bulbil** [bulbil/linked.art#2]
Update styles for code blocks and mermaid diagrams to look more similar to linked art production

**Comment by buccalon** [comment]
@bulbil I don't find the syntax highlighting very useful, shall we move forward just with tooltips? #8

Here is the current look in production:
<img width="929" alt="image" src="https://github.com/user-attachments/assets/7537aba7-8645-45ec-8a4c-8f7dd15f1161">

And here is the current version within mkdocs-material:
<img width="714" alt="image" src="https://github.com/user-attachments/assets/7fc79185-2951-479f-b401-193e8569b992">

**Comment by buccalon** [comment]
Thinking of a better approach, I'll match colors between the crom output and the theme JSON code block:
<img width="711" alt="image" src="https://github.com/user-attachments/assets/416fb172-ef6f-40e7-8d36-07f83e6bf778">
